import './globals.css'

import type { Metadata } from 'next'
import { AppProps } from 'next/app'
import Head from 'next/head'
import { Roboto } from 'next/font/google'

import { NextAuthProvider, Theme, AnimateProvider } from "./providers";


const inter = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Bard4Free',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <NextAuthProvider>
            <AnimateProvider>
              {children}
            </AnimateProvider>
          </NextAuthProvider>
        </Theme>
      </body>
    </html>
  )
}
