# Generated by Django 4.1.7 on 2023-07-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_follower_alter_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
