# Generated by Django 4.1.7 on 2023-03-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_name_auction_list_title_auction_list_catagory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='image',
            new_name='image_url',
        ),
    ]
