# Generated by Django 4.1.7 on 2023-04-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_image_auction_list_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('catagory', models.CharField(blank=True, max_length=64, null=True)),
                ('imageURL', models.URLField(blank=True, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('highestBidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='auction_list',
        ),
        migrations.DeleteModel(
            name='auction_list',
        ),
        migrations.AddField(
            model_name='comments',
            name='auctionList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionList', to='auctions.auctionlist'),
        ),
    ]
