# Generated by Django 4.1.7 on 2023-04-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlist_remove_comments_auction_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='auctionList',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='auctionList', to='auctions.auctionlist'),
            preserve_default=False,
        ),
    ]
