# Generated by Django 4.1.7 on 2023-04-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchList',
            field=models.ManyToManyField(related_name='list', related_query_name='user', to='auctions.auctionlist'),
        ),
    ]
